# Generated by Django 2.2.6 on 2019-10-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keymap',
            name='hostname',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
